### PR TITLE
adding container tools to reproducibility page

### LINKED ISSUE #6: Contribute.md link
hey @FelixHenninger ! I had thought that you forgot to add the contribute.md document to the repo,  but I just found it under ` content/change/community/contribute.md`. You can assign me to fix this link - I'm doing a PR now! Just a quick question - are there instructions for developing locally? What kind of server (jekyll, other?) are you using when you develop?

### PR DESCRIPTION
**Pull request by vsoch**
This PR will close #6 by fixing the link to the contribute.md page, and do the following:

### Reproducibility Sections
I've added categories (subsections) to the list of open source tools, because there are **many** resources that should be discovered here, and they are likely to be best organized in these subsections. Currently, my changes add "Scientific Programming" to describe python, R, etc., and then "Containers" to describe a subset of reproducible container technologies. E.g.:

image

Another thing I am thinking about - there isn't any AUTHORS.md file or similar - how do you want contributors to the repo to add their contribution history?  As always @FelixHenninger, this site is totally beautiful and I am just going to leave the server main page open on my computer to stare at the colors ;)

### CODE REVIEW

**Comment by FelixHenninger** [comment]
Hi again, and thank you sooo much for adding this! I totally agree that we're way too thin on computational reproducibility, and containers in general, so all of these links should without any doubt go in.

That being said, I'm imagining, e.g. my students, reading the section, and would love to provide a bit more context. When we first sat together and drafted these pages in our department, we had the tendency to play jeopardy a bit, and I'd like to challenge you to do the same: What's the question that this section is answering? Could it be something like "how can I make sure that my analysis runs on somebody else's machine, in a couple years time?". Why specifically are containers the answer to this? Would it make sense to explain containers in general, and add an info box regarding the different implementations?

I don't have the answer to any of these questions -- you're the expert here, and I would not want to slow you down (not that I ever could), but if I may, I'd love to take a step back together, and add a few more sentences regarding what these technologies do.

I hope that makes sense -- thanks again for your help! -Felix

**Comment by FelixHenninger** [comment]
Oh, and I just remembered reading [this preprint](https://doi.org/10.17605%2FOSF.IO%2FMF82T), which I think does a good job of motivating containers in general, do you think that would be a good addition? (I'm not sure I like the CodeOcean-centricness, and I guess you probably won't). Is there more literature like this?

**Comment by vsoch** [comment]
hey @FelixHenninger ! I think I talked about this a bit in an email I just sent to you, and I'll repeat here! I think we would want this primary page to have a quick description like you described (e.g., Why containers are important) before the section, but then the more verbose description provided in subpages. Step 1 is to add these categories / links, and then the subpages can follow! I'll add a header for the containers section with a brief description right now - hold tight!

**Comment by vsoch** [comment]
Another quick note is that most of the links should provide this background and rationale, if the documentation is good to begin with. For example, SCIF opens with questions to the user as you suggested, e.g., "How does SCIF relate to containers? What will I learn reading this?" It comes down to if this page is serving as a complete resource (hard to maintain) versus a curated resource of quality links to resoueces, each with their up to date documentation.

**Comment by vsoch** [comment]
okay, I added a description and resources section! 

image

And of course the best source of understanding comes from each of the resources pages, individually (and note this is different from some of the links for R, python, that just assume you start there knowing why you are there!)

I think having a description --> listing --> resources is a good start, and eventually we can move toward having subpages for different topics where needed. I'd be happy to help here too.

**Comment by FelixHenninger** [comment]
Wow, I love 💗 that container resources section, thanks so much! Also, I see all of your points (thanks for your great email!), and I'm pretty much sold on your proposed structure. What I'm wondering is whether it would make sense to put the implementations in the boxes for tech-addicts (if I may) like us to skim? (I very much also identify with jumping over the paragraphs)

Apart from that, I think this is perfect, happy to merge, and might add some more resources over the next days if that's ok?

**Comment by vsoch** [comment]
Totally ok! Please hack up any and all content that I'm contributing! When you say:

> put the implementations in the boxes for tech-addicts

what do you mean?  If you want to open a new issue and describe this (and assign me) I'll gladly open a PR to give it a go :)

**Comment by FelixHenninger** [comment]
Sorry, what I was thinking about was putting the specific tools in the `tip` box/inset, and the more general discussion as a regular paragraph (which probably suits its somewhat more bland nature) -- what do you think?

**Comment by FelixHenninger** [comment]
Oh, and while I'm at it, I have two more questions if I may, because you're much better at GitHub collaboration than I am (don't let me keep you from more important things though):

* When I'm working for myself, I tend to rebase instead of creating merge commits, so I've setup the repository to rebase and merge (fast-forward). However, I'm not sure I like how GitHub splits the ownership in this case (e.g. on 24df643c3d6f7d34d7c42e1a45f72d4aff34c164). Do you have a preference or recommendation?
* If, in the future, we wanted to go back and forth on some change before committing to master, we would probably use a separate branch, right?

**Comment by vsoch** [comment]
oh interesting! I would advocate for the other way around - the listing is the concise listing of the open source tools, and the resource are extra helping documentation for those that want it (outside of the link provided by the resource). So in my implementation, the box has extra resources (papers) and the links themselves are the software (the point of focus that the researcher would want to use!)

**Comment by vsoch** [comment]
Yeah I would be careful about rebase, because it lists one person as the author, and you as commit, and I am not sure that gives proper credit. It's better to do the:

```bash
feature branch --> PR --> review --> merge
```

and then pull down into your local branches to update.

**Comment by FelixHenninger** [comment]
Oh, Zenodo integration is a fantastic idea! I'll put hooking it up on my list -- I'm not sure my personal account will be the home of this repository for long, so my hunch is it might pay to wait a little.

**Comment by FelixHenninger** [comment]
And I very much see your point regarding authorship -- I also dislike how GitHub handles that by default. I'll pull in your branch as a remote in my local repo, and fast-forward so I can see what's going on.

Ok, merging now!

**Comment by vsoch** [comment]
woohoo! If you want to create an organization around this tooling and give me some level of permissions, I'd be happy to do the Zenodo stuffs via PRs, and probably it would be good to add it as a resource too!

**Comment by FelixHenninger** [comment]
Ok, I hope I've done this correctly! Massive thanks again for your help and assistance, it's awesome (as always) to have you around!

Regarding the organization -- I think you're right that this repository should move to some larger entity, so that I can also propose edits using pull requests like everyone else, and I think in the mid-term, there should be a slightly more formal editing/review process. We have a national open science initiative that might be able to pull of something like that, and I've been trying to pitch it to [SIPS](http://improvingpsych.org/), which I think would be the best home in the long term -- we'll have to see who bites. In either case, I think it would be awesome to have you around if you like! There are very few people who understand both the tech and the content like you do.

**Comment by vsoch** [comment]
That's so kind of you to say! :D  Yes please ping me when you find a home - I can help _build all the things_ ;)

**Comment by vsoch** [comment]
Here is a rundown of the commands I just did to update my local branches. I think rebases / fetch / other ways are possible to go about this, but I do the simple way with push / pull / checkout, etc.

Here I'm starting on a feature branch, and it was just merged (and note I'm going to delete it to keep my remote clean of merged branches). The first thing I want to do is again checkout master:

```bash
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
```
I now know that I want to interact with your repository, we might call this "upstream" so I check my git config remotes to see if I have it:

```bash
$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:vsoch/open-science-knowledge-base
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
I don't! I just have "origin" which refers to my fork on vsoch. So, normally I would just open that file and write this in, but there is a command to easily add a remote:

```bash
# git remote add [name] [url]
$ git remote add upstream https://github.com/FelixHenninger/open-science-knowledge-base
```
Note that I am using https, which means I can just pull, because I use SSL. If you want to add a remote with SSL, the address would be like mine (` git@github.com:vsoch/open-science-knowledge-base`)
We can now confirm it's added!

```bash
$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:vsoch/open-science-knowledge-base
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "upstream"]
	url = https://github.com/FelixHenninger/open-science-knowledge-base
	fetch = +refs/heads/*:refs/remotes/upstream/*
```
And now (for sanity check) I again check the branch I'm on (should be master)

```bash
$ git branch
  add/expfactory+scif
* master
```
I know this PR was just merged, so I want to update my local master with the master here. Since your remote is called "upstream" that's what I refer to (and this is a standard I use across my respositories)

```bash
$ git pull upstream master
From https://github.com/FelixHenninger/open-science-knowledge-base
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream/master
Updating c084daf..a5d5688
Fast-forward
 README.md                              |  2 +-
 content/analyze/reproducibility.md     | 21 +++++++++++++++++++++
 content/change/community/contribute.md | 62 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 3 files changed, 84 insertions(+), 1 deletion(-)
```
I can now push these changes to my master (origin) to make sure it's in sync. This is where I think there is a more concise command - I don't use it :P 

```bash
$ git push origin master
X11 forwarding request failed on channel 0
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:vsoch/open-science-knowledge-base
   c084daf..a5d5688  master -> master
```
What is important, at the end of the day, is that the git commit history looks as I'd want / expect!

image

I've seen others copy pasting code (and taking credit for it) or doing other tricks so the original author is not given credit for some portion, and it makes me hugely uncomfortable because it feels morally wrong. I will say when things get complicated there could be instances when some sort of cherry picking is needed (so one person authors, someone else commits) but these should be avoided if necessary! Cherry picking is usually the result of doing something wrong and then having to fix it, so we can just try to avoid that, lol.

**Comment by FelixHenninger** [comment]
Hej Vanessa, thank you sooo much for this detailed explanation! I just worked through it, and it makes total sense and will come in handy for sure -- I'm going to make a local copy so I can refer back to it.
Also, @luisahorsten and I were wondering how to do this properly the other day, and I think you might have just answered many of her questions too.

So please let me send my heartfelt thanks halfway around the world -- for your help and generosity and for sharing your awesomeness today; it's been a huge pleasure to discuss things and learn from you! I'm out for the day, but you have quite a bit ahead of you yet -- here's hoping it's a happy and interesting one. See you around!

-Felix

**Pull request merged**
