### PR TITLE
Open Protocols + minor addition

### PR DESCRIPTION
**Pull request by luisahorsten**
Hi Felix,

it looks like this time this PR is working a lot better. I hope? 

I found some stuff about study protocols that I thought were worth including. That new page is probably not even close to being finished but I wanted to see whether I could make a PR work now. Also, I haven't included the page in the index yet, because I first wanted to see whether you think this would be a useful page.

Best, Luisa

### CODE REVIEW

**Comment by FelixHenninger** [comment]
Wow, that looks great! I'm ready to merge when you are -- in case you haven't already, please briefly [check that the page looks as it should](https://deploy-preview-9--oskb.netlify.com/share/open-protocol/).

**Comment by FelixHenninger** [comment]
As I wrote above, I think this can be included directly (feel free to add the link from the index, or I can do that for you) -- if you can take another look at the contents (after we get it merged), what I stumbled over was that I myself wasn't familiar with the term 'protocol' at all, and (to my naive mind) the protocols seem to be for very different purposes -- DRESS seems to be mostly concerned with analysis, while the BMJ is concerned with methods sections (and from there, I liked the link to the [spirit statement](http://www.spirit-statement.org/)), and protocols.io with benchtop experiments.

I wondered if we could introduce the concept some more, and motivate more clearly what's in a protocol for empirical researchers -- is it a template for a methods section? An abbreviated methods section? A checklist? I'm not sure I could answer that after looking at this for a few minutes.

**Comment by FelixHenninger** [comment]
Ok, I merged this (and managed to insert a commit of my own in the process, somehow), feel free to link the page on the front page and in `mkdocs.yml`, or let me know and I'll hook things up.

Thanks again! -Felix

**Comment by luisahorsten** [comment]
Hey Felix, thanks for your feedback! 

I understand your confusion and agree that at the moment the page may not be self-explanatory yet. To me, a protocol describes the process of how you obtain your results. So depending on one's field of research, I guess this could be different things - either the way the experiment is set up, or the data is analyzed or a mixture of both, or ... So all of the included links suggest how one can document their research process so that other researchers can easily reproduce it. Though I agree concerning the DRESS Procotol - I wasn't sure whether it would be better to link to it on the Analysis page, but I felt like it is concerned with the step after analyzing data, when it comes to actually sharing. 

I don't know, does my rambling make any sense to you at all? :smile:

**Pull request merged**
