### PR TITLE
Some (more or less random) additions

### PR DESCRIPTION
**Pull request by luisahorsten**
I'm not exactly sure why all the commits I pulled from your repo are included in this pull request... Still trying to work things out, I guess :D Sorry for causing any inconvenience...

Also, I'm not sure if I should make a pull request for meaningful units or randomly throw commits together like I am doing here...? :confused:  

BTW: Holy cow, I'm amazed by how much has changed here over last month :astonished: Fantastic work!

### CODE REVIEW

**Comment by FelixHenninger** [comment]
Hej Luisa,

wow, thanks a *lot* for putting all of this together, there's loads of awesome stuff in there -- I loved the link to the checkpoint package in particular, I had no idea something like that even existed, that would have saved me days of work!

Regarding the other changes, my feeling is that many of your suggestions are indications that we need to change the overall structure. For example, with the link to Ulrich Schimmack's webpage suggests to me that we need a new page on Questionable Research Practices -- what are they, how common are they, how can we prevent them? Would you be willing to consider pulling this content from the preregistration page and expanding it a bit? (maybe along the lines of Schimmack's post, though I think we can do a bit better, for example a more concise job with much better sourcing and examples, and I think you also know enough to get started on your own). I would be super-happy to help you outline such a page if you like, or maybe you could [create an issue](https://github.com/FelixHenninger/open-science-knowledge-base/issues/new) where we could collect resources without going through pull requests?

Similarly, I think the [TIB FAQ](https://zenodo.org/record/1173546#.WyEIVKlCRXh) and the [DGPs recommendations](http://www.dgps.de/fileadmin/documents/Empfehlungen/Data_Management_eng_9.11.16.pdf) are fantastic additions, but rather Germany-specific. What do you think about adding links on the respective pages (privacy and licensing)? I don't think we need a disclaimer beyond what we have in the imprint since we're only linking to third-party resources (who, in the case of TIB, also have their own disclaimers in the documents)

Ok, so much for now -- these are just my random thoughts, please don't hesitate to let me know where I'm wrong!

Best, and thanks again, -Felix

**Comment by FelixHenninger** [comment]
Oh, and we need to get the pull requests under control! Holy moly is GitHub creating a mess here. Let's sit down and figure this out if you have a moment sometime, I need to learn this stuff too!

**Comment by luisahorsten** [comment]
Hi Felix,

thanks for putting up with my mess and for your feedback! I'm not sure it's GitHub creating the mess, tbh... 😬 When I just tried to synchronize, weird things happened again. I thought I followed @vsoch 's guide from the other day, but then there were merge conflicts and I got lost.  And then I was apparently 32 commits ahead of you, though I did nothing more than try and sync... So I just deleted my fork and re-cloned it. Fresh start can't hurt, can it? Let's see how it goes from here. I refuse to spend more time fighting against git than actually contributing.

Going more into depths concerning QRPs might be a good idea, I'll definitely look into that! About creating an issue - would that mean, we collect thoughts and ideas there and you would have to integrate them into the OSKB? Sounds like that would cause more work for you. (Though I guess, if we don't get the other mess sorted out it might actually save you some work... Ugh.)

**Comment by luisahorsten** [comment]
Oh, and concerning the page about legal aspects - that was one of the topics I did on Franziska's behalf. Of course the overall structure has advanced to a great extent since we allotted topics for contribution, so it will probably work to add links to existing pages. Both links cover mostly aspects that would go under licensing, would you agree? I don't see how either of them contributes a lot to privacy that hasn't been mentioned there before.

**Comment by FelixHenninger** [comment]
Hej Luisa,

no worries, sorry for messing up your commit flow!

> I refuse to spend more time fighting against git than actually contributing.

That's great, please continue doing that! I can pull commits from your repo, but the rebasing back is a problem we should solve. I think we need to get this `git` collaboration thing figured out stat, I agree that this is causing too much overhead :-/ . This is a shame really, it's such a nice thing when it works.

> Going more into depths concerning QRPs might be a good idea, I'll definitely look into that! About creating an issue - would that mean, we collect thoughts and ideas there and you would have to integrate them into the OSKB? Sounds like that would cause more work for you.

That sounds awesome, please do! I think an issue would make sense if we take some time to outline the structure/argument of the entry (and I probably have a few links to add), but if you want to go right ahead, please don't let me slow you down.

> Oh, and concerning the page about legal aspects - that was one of the topics I did on Franziska's behalf. Of course the overall structure has advanced to a great extent since we allotted topics for contribution, so it will probably work to add links to existing pages. Both links cover mostly aspects that would go under licensing, would you agree?

Ah, I see now, that makes total sense! 

It would be great if we could get everybody started with their entries when you come back -- @MattiMeyer has made an awesome page on bayesian stats, I'll push that someday soon, and I would love to hear your thoughts on that, too!

Ok, so much for now -- you're heading to the wilderness up north, right? Safe travels, and have a great time!

-Felix

**Comment by FelixHenninger** [comment]
I'm closing this for now, as I think we've dealt with all of the issues for the moment. Please correct me / undo this if there's something we still need to fix.

**Comment by vsoch** [comment]
hey in the future if there is trouble with commits I can offer to help, I know it's frustrating!

**Comment by FelixHenninger** [comment]
Wow, thanks, Vanessa, that's super-kind! Do you have an intuition about a good way to learn/practice this? I'm tempted to setup a local installation of [Gogs](https://gogs.io/) or something similar and spend an afternoon creating messes together and untangling them again, put surely there's a more principled approach? 😉

**Comment by vsoch** [comment]
I think just, the next time it happens, pinging me on the issue and we can walk through debugging it. I shudder to think of trying to artificially set it up, haha.

**Comment by vsoch** [comment]
it's like, if I had a cat. At some point or another he's going to do his cat "swatty thing" and knock over a glass of milk on the container (well maybe more like hot cocoa). I'd then call the masses and teach about cleaning up the hot cocoa. But I wouldn't go out of my way to knock over my own hot cocoa to do the same :)

**Comment by vsoch** [comment]
Oh! And I've set up Gogs! But to develop something else - it's actually another **entire** project I'm going to get into when I have more free time - version control for... let's just say other (unexpected, atypical) things :)

**Comment by luisahorsten** [comment]
Hi Felix,

> I think an issue would make sense if we take some time to outline the structure/argument of the entry (and I probably have a few links to add), but if you want to go right ahead, please don't let me slow you down.

No, this sounds very reasonable! I haven't had the chance to put much thought into the potential entry yet, but I also think we need to figure out how to fit such an entry in here, since all the other entries are concerned about *how* to do things instead of how *not* to do things. Also, keep 'em links coming! :wink: 

>> Oh, and concerning the page about legal aspects - that was one of the topics I did on Franziska's behalf. Of course the overall structure has advanced to a great extent since we allotted topics for contribution, so it will probably work to add links to existing pages. Both links cover mostly aspects that would go under licensing, would you agree?

> Ah, I see now, that makes total sense!

:smile: So now what do you think should we do about those links? Dedicate an entry of its own to it or add them to the licensing page?

> It would be great if we could get everybody started with their entries when you come back

Absolutely! Has anybody sent you anything yet? Should I send a reminder e-mail? 

> you're heading to the wilderness up north, right?

Yes, indeed. But I'm taking my laptop and will definitely arrange time to get some work done (just in a prettier surrounding :grinning:)

Talk to you soon!
Best,
Luisa

**Comment by FelixHenninger** [comment]
Hej Luisa,

thanks a lot for your comments! (sorry, I missed this one because of the closed PR, maybe we should start a new one? ;-) )

> So now what do you think should we do about those links? Dedicate an entry of its own to it or add them to the licensing page?

Thanks for keeping track of this! In my head (/wishful thinking), we already put this information somewhere (and distributed it across pages, which I personally tend toward). I'll dig into our commit tree, maybe it's lost somewhere there.

> Has anybody sent you anything yet? Should I send a reminder e-mail?

I have a kick-ass entry on Bayesian stats from @MattiMeyer, but nothing beyond. I think a brief reminder would be cool, also directing everybody to take a look at the current state before they submit, and (kindly) to make sure they phrase their page as a question and then proceed to answer it ;-) .

> [_I'm heading into the pristine wilderness of Scandinavia for holidays before starting grad school_] but I'm taking my laptop and will definitely arrange time to get some work done

Yeeeah, I'm going to have to stop you there ;-). I mean I can't force you, but I'm going to go as far as I can: No way is this important enough to get in your way -- let's sit down in September and get this done in a focussed way, whatcha think?

Kind regards, and have a relaxing and awesome time up north!

-Felix

**Pull request closed without merging**
